apiVersion: v1
kind: Secret
metadata:
  name: jobfit-secrets
  namespace: jobfit
type: Opaque
stringData:
  JWT_SECRET: "local-k8s-change-me-before-sharing"
  ANTHROPIC_API_KEY: ""
  POSTGRES_USER: "jobfit"
  POSTGRES_PASSWORD: "jobfit"
  POSTGRES_DB: "jobfit"
  HUNTER_API_KEY: ""
  GMAIL_CLIENT_ID: ""
  GMAIL_CLIENT_SECRET: ""
  GMAIL_REFRESH_TOKEN: ""
  REED_API_KEY: ""
  ADZUNA_APP_ID: ""
  ADZUNA_APP_KEY: ""
